# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_S_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=40)),
                ('Adress', models.CharField(max_length=40)),
                ('Note', models.TextField()),
                ('date', models.DateField()),
                ('c_s_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.C_S_Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('imagepath', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='c_s_mapping',
            name='c_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AddField(
            model_name='c_s_mapping',
            name='s_c_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.Subcategory'),
        ),
    ]
